version: "3"

volumes:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
