# syntax = docker/dockerfile:1

ARG NODE_VERSION=18.17.1
ARG PORT=3000

FROM node:${NODE_VERSION}-alpine as base

RUN apk --no-cache add openssh g++ make python3 git

ENV NODE_ENV=development

WORKDIR /app

COPY --link package.json yarn.lock /app/

# Build
FROM base as build

RUN yarn


# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD [ "yarn", "run", "dev" ]
