# syntax = docker/dockerfile:1

ARG NODE_VERSION=16.20.2
ARG PORT=3000

FROM node:${NODE_VERSION}-alpine as base

RUN apk --no-cache add openssh g++ make python3 git

ENV NODE_ENV=development

WORKDIR /src

COPY --link package.json yarn.lock /src/

# Build
FROM base as build

RUN yarn install --ignore-engines

# Run
FROM base

COPY . /src/
COPY --from=build /src/node_modules /src/node_modules

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=$PORT

EXPOSE $PORT

CMD [ "yarn", "run", "dev" ]
